<?php
/*
 * Copyright (C) 2019 Paymentsense Ltd.
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 3
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * @author      Paymentsense
 * @copyright   2019 Paymentsense Ltd.
 * @license     https://www.gnu.org/licenses/gpl-3.0.html
 */
?>
<!DOCTYPE html>
<html>
<head>
  <title><?php echo $this->__('3-D Secure Authentication is required to complete your payment.'); ?></title>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  <style>
    html,body {
      margin:0;
      padding:0;
      width:100%;
      height:100%;
      display:table;
    }
    .wrapper {
      text-align:center;
      display:table-cell;
      vertical-align:middle;
    }
    .notice {
      padding:16px;
    }
    p, form {
        font-family: Lato,helvetica neue,Verdana,Arial,sans-serif;
    }
    input#submit {
        border: 0 solid #66951c;
        cursor: pointer;
        font-weight: 400;
        line-height: normal;
        margin: 0;
        position: relative;
        text-decoration: none;
        text-align: center;
        -webkit-appearance: none;
        display: inline-block;
        background-color: #7fba23;
        color: #fff;
        border-radius: 3px;
        transition: background-color .3s ease-out;
        padding: .5rem 1rem .6rem;
    }
  </style>

</head>
<body>
<div class="wrapper">
  <div class="notice">
    <p>
        <?php echo $this->__("3-D Secure Authentication is required to complete your payment."); ?>
    </p>
  </div>
  <div class="form">
      <?php echo $this->generateForm(); ?>
  </div>
</div>
<script type="text/javascript">
  window.setTimeout(
    function() {
      document.getElementById("<?php echo $this->getButtonId(); ?>").click();
    }, 3000
  );
</script>
</body>
</html>